version: "3.8"

services:

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ss-quiz-backend
    command: /bin/bash -c "python manage.py migrate; python manage.py collectstatic --no-input; python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: ss-quiz-db
    env_file: .env
    restart: unless-stopped
    ports:
      - "8001:5432"
