version: "3.8"

services:

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insure-web
    command: /bin/bash -c "python manage.py migrate; python manage.py collectstatic --no-input; python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
      - esearch

  db:
    image: postgres
    container_name: insure-db
    env_file: .env
    restart: unless-stopped
    ports:
      - "8001:5432"

  esearch:
    container_name: insure-search
    image: elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    restart: unless-stopped
    ports:
      - "9200:9200"
