version: "3.8"

services:

  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: ss-quiz-backend
    command: ./docker/backend_setup.sh
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: ss-quiz-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    restart: unless-stopped
    ports:
      - "8001:5432"
